
############################################
#  ENVIRONMENT SETUP
############################################


# the most recent Unity version on Netsotrage ist 5.3.5f1 as if 4th Aug 2016

env:
  global:
  - APPNAME="BM.Muse_MuseStatsIos"
  - UNITY3D_VERSION="5.3.5f3"   
  - 'DEVELOPER_NAME="iPhone Distribution: NAME_OF_THE_DEVELOPER (CODE)"'
  - PROFILE_UUID=PROVISIONING_PROFILE_UUID
  - APP_Version="160723"
  
  

# Handle git submodules yourself
git:
    submodules: false

before_install:
#- chmod a+x ./Scripts/install.sh
#- chmod a+x ./Scripts/build.sh
# Objective-C support
language: objective-c
 
# Latest Xcode		
osx_image: xcode7.3		

#xcode_project: Unity.xcodeproj		
#xcode_scheme: Unity		

#xcode_sdk: iphonesimulator9.3		

rvm:		
- 2.1.2		

#xcode_project: libmuse_5.8.0/ios/examples/MuseStatsIos/MuseStatsIos.xcodeproj
#xcode_scheme: MuseStatsIos

# Install the unity binaries for compilation 
install:	
    - wget "http://netstorage.unity3d.com/unity/960ebf59018a/MacEditorInstaller/Unity-${UNITY3D_VERSION}.pkg"
    - wget "http://netstorage.unity3d.com/unity/960ebf59018a/MacEditorTargetInstaller/UnitySetup-iOS-Support-for-Editor-${UNITY3D_VERSION}.pkg"
    - sudo installer -dumplog -package "Unity-${UNITY3D_VERSION}.pkg" -target /
    - sudo installer -dumplog -package "UnitySetup-iOS-Support-for-Editor-${UNITY3D_VERSION}.pkg" -target /

############################################
#  BUILD PHASE
############################################
    
    
#before_script:
#- ./scripts/travis/add-key.sh

#after_script:
#- ./scripts/travis/remove-key.sh

#after_success:
#- ./scripts/travis/testflight.sh

############################################
#   DEPLOYMENT AND NOTIFICATION
############################################


before_deploy:
  - export RELEASE_PKG_FILE=$(ls *)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: Mp5qTPzTyjBp40XQWymKbEW6IZiQpxwljDTF3pLs0kNEuT9EW41apgVLKNNDgmlSnHjWlxx5O6SzBCPLEu62R+yoo8vhG837fgf1M01mBC4IYfCfy7dFoHqtH8qZ0hgUFawx12MB5YFAQMYes0eeIo2YMatQxAFW8avqbrTjk3spDWuG4jSz+opvNmKGlVeLPxgnoadGbYUTEiqJswBllfc8pyVFiJGgHagQ74B1c4ZtwCWbO0tmY007wj5BAX5VkHlPtfK045vW44A86CqKDgdfTUK+k90sLqLuNujAmNYGC38SOLREytVdBce4w/xRr3Y+YzRcCr3H9zP8BRVvu8kwUgy5VcyMaS/ZK4aUH2SczTaz1gG086RoBERVkcHwMxbMusiwpjOq6LWHb/wzsPmSXJ9SMUY5/gCQAm9uLkf3rvDOekQL9s0XGgq6WBEW4bI+DPnKdWGk5s/qoZkAGKqfw9ywVlFpZZNSi8QFGA9IduKbdJ3VUwdUZTeWrzLVghLF/CDUbPsZv/7CZkZluHWNrz9TItVBD1Ter0PhSv3N/y/BuYlCj0oc/WHbJOMOFLMXvDdOALCTdt2cpBmBwAVNf199dch/8UGCAZV4j1xdTQd75qTdSpjaYIRUawRf/KPktIfF6s6E0eAbjd3xmsmRYVxgJvDonGVJGc+EePQ=
#  file: "$OUTPUTDIR/$APPNAME.ipa"
  file: libmuse_5.8.0/ios/examples/MuseStatsIos/MuseStatsIos.xcodeproj
  skip_cleanup: true
  on:
    repo: BrainModes/BM.Muse
    tags: true
#  overwrite: true

branches:
  only:
    - master
    - stable
    - release

notifications:
  slack:
    secure: LLnhnu2+d6jcJ1T1uF+qvYX+FvNvj+bXia84AmuzSrfAxrqd5K9a6v62LFyA5u+2I5ZdQ4dLBlSuy3y3nSgM+io2/sIkxUWJmozXk9Z7HhlBwyDum7SBor30lQ6YsL2+19nLDv10QbAYP3IedSXJLVQXMknWhujMExnf88ohTdtMjqMQJRUV/9NX/Habh4nB61lrqW3lEkNky0RJAQ22SqpBepVLisUwOfDCj4E78VtGRodGEAwFR+0IYWRN4KXoxivDfobw2MaYctXr5koBHwtv8fe/tu3oX0Dqmzg2hB9YJeJxGpITXc24FbaJAmE26rJxuLRizqZK2QKRCVbZeNY0pKwgYOtF7QjELuAL5BwQ3h/gRu0lVTmLmRea9Grmez/wGz9yAmBHVcZiXeOzYtCOnR9WtrJHNCSK7K47JOzXYwsT2DuQngAHtSEpH6LxsE8iN+NWcZa/E73RwXsjwA2KiJMIh3xZcleSwOUu4je9fTKN8bvi0hQfBbgXKVKqDx3jgTAhmdhH9psWhFb5yCfYTcgLrkgmF5BT9IUzzvR33mZzOBloG0x4AzOc3mk/fJ4bCPdfkpu7RYvuaR2d57Go/ftrCgR9h8IfjxJ2m8H/wbF3wvG2EbW/gDQ1cz5mCCJ1raH5a1GKImcAgY/K9sATMIvUulDmR5V9kmEEXIo=
  email:
    recipients:
      - daniel@brainmodes.net
