// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in a Gyro data packet
 * \if ANDROID_ONLY
 * \sa com.choosemuse.libmuse.MuseDataPacketType.GYRO
 * \sa com.choosemuse.libmuse.MuseDataPacket.getGyroValue()
 * \endif
 * \if IOS_ONLY
 * \sa \link IXNMuseDataPacketType::IXNMuseDataPacketTypeGyro IXNMuseDataPacketTypeGyro\endlink
 * \sa IXNMuseDataPacket::getGyroValue:
 * \endif
 */
typedef NS_ENUM(NSInteger, IXNGyro)
{
    /** Forward/Backward axis value in milliG */
    IXNGyroForwardBackward,
    /** Up/Down axis value in milliG */
    IXNGyroUpDown,
    /** Left/Right axis value in milliG */
    IXNGyroLeftRight,
};
